image: "mikaelfk/bachelor_ci:1.0"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3.10 -V               # Print out python version for debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - Test

pytest:
  stage: Test
  script:
  - pip3 install pytest python-dotenv
  - echo "JHOVE_PATH=/usr/bin" > .env
  - pytest tests
